import { IWatch } from '../interfaces';

export const watchData: IWatch[] = [
  {
    id: 1,
    brand: 'Casio',
    name: 'CASIO MTG-B2000D-1AER',
    price: 1678,
    stock: 11,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      'Case color - silvery; Case shape - round; Dial color - black; Indication type - pointer; Glass - sapphire; Assembly factory - Japan; Movement type - quartz; Material - steel; Bracelet / Strap - bracelet; Thickness - 15.9; Style - Sport; Water protection - 200 WR;',
  },
  {
    id: 2,
    brand: 'Casio',
    name: 'CASIO EQW-A2000HR-1AER',
    price: 968,
    stock: 24,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      'Movement type - quartz; Water protection - 100 WR; Case shape - round; Dial color - black; Glass - sapphire; Case color - silvery; Indication type - pointer; Style - Sport; Bracelet / Strap - strap; Leather material;',
  },
  {
    id: 3,
    brand: 'Casio',
    name: 'CASIO Pro-Trek PRW-61Y-3ER',
    price: 669,
    stock: 41,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      'Case color - black; Case shape - round; Dial color - green; Type of indication - pointer; Glass - mineral; Material - polymer; Bracelet / Strap - strap; Thickness - 14.7; Style - Sport; Water protection - 100 WR;',
  },
  {
    id: 4,
    brand: 'Casio',
    name: 'CASIO G-Shock GW-9400-1ER',
    price: 511,
    stock: 47,
    clockFace: 'digital',
    mount: 'strap',
    description:
      'Stylish and durable, the Casio G-Shock watches stand out from the rest. The unique design of the watch will withstand any load. The watch uses only the most modern heavy-duty materials that provide unsurpassed protection. G-Shock watch features include an automatic calendar, stopwatch, alarm clock, timer, world time, auto backlight, and more. Some models have a notebook. This series of watches is perfect for people who play sports and closely follow modern fashion.',
  },
  {
    id: 5,
    brand: 'Casio',
    name: 'CASIO Pro Trek PRG-270-1ER',
    price: 300,
    stock: 69,
    clockFace: 'digital',
    mount: 'strap',
    description:
      'Casio ProTrek wristwatches are designed specifically for the conquerors of life\'s heights. Casio ProTrek watches are a real find for tourists, travelers and all those who cannot imagine their life without adventures. You will be pleasantly surprised by the presence of "Three sensors" (built-in barometer, compass, thermometer), as well as an altimeter, which makes ProTrek your true friend on any journey.',
  },
  {
    id: 6,
    brand: 'Citizen',
    name: 'Citizen BN7020-09E',
    price: 2896,
    stock: 17,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "Type - Man's; Movement - Quartz; Dial type - Pointer; Glass - Sapphire; Case shape - Round; Case material - Stainless steel with PVD coating; Water resistance - 200 m; Strap/bracelet material - Rubber; Case dimensions (HxW) - 46.00x46.00 mm mm;",
  },
  {
    id: 7,
    brand: 'Citizen',
    name: 'Citizen CC9015-54E',
    price: 2131,
    stock: 21,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      "Type - Man's; Movement - Quartz; Dial type - Pointer; Fastening type - Bracelet; Glass - Sapphire; Case material - Steel; Water resistance - 100 m; Strap/bracelet color - Silver; Strap/bracelet material - Steel; Case dimensions (HxW) - Case diameter 43.5 mm, thickness 13.1 mm mm; Warranty - 12 months; Body color - Silver;",
  },
  {
    id: 8,
    brand: 'Citizen',
    name: 'Citizen AT8234-85A',
    price: 934,
    stock: 47,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      "Type - Man's; Movement - Quartz; Dial type - Pointer; Glass - Sapphire; Case shape - Round; Case material - Titanium; Water resistance - 100 m; Strap/bracelet material - Titanium; Housing dimensions (HxW) - 45.00x45.00 mm mm; Weight - 89.00 g; Warranty - 12 months;",
  },
  {
    id: 9,
    brand: 'Citizen',
    name: 'Citizen CB0260-81E',
    price: 712,
    stock: 44,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      "Type - Man's; Movement - Quartz; Dial type - Pointer; Glass - Sapphire; Case shape - Round; Case material - Titanium; Water resistance - 100 m; Strap/bracelet material - Titanium; Case dimensions (HxW) - 40.00x40.00 mm mm; Warranty - 12 months;",
  },
  {
    id: 10,
    brand: 'Citizen',
    name: 'Citizen AS2053-11A',
    price: 573,
    stock: 55,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "Type - Man's; Movement - Quartz; Dial type - Pointer; Glass - Sapphire; Case shape - Round; Case material - Stainless steel with PVD coating; Water resistance - 100 m; Strap/bracelet material - Genuine leather; Housing dimensions (HxW) - 39.00x39.00 mm mm; Warranty - 12 months;",
  },
  {
    id: 11,
    brand: 'North Edge',
    name: 'North Edge Gavia 20BAR',
    price: 225,
    stock: 72,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      "Type - Man's; Movement - Quartz; Style - Sports; Dial type - Pointer; Glass - Mineral; Dial type - Arabic numerals; Case shape - Round; Case material - Steel; The main color of the dial is Blue; Water resistance - 30 m; Strap/bracelet color - Silver; Strap/bracelet material - Steel; Case dimensions (HxW) - 48x15 mm; Movement characteristics - Gavia 2 North Edge (Japan); Warranty - 12 months; Body color - Silver; Case diameter - 48 mm;",
  },
  {
    id: 12,
    brand: 'North Edge',
    name: 'North Edge Apache 5BAR',
    price: 97,
    stock: 64,
    clockFace: 'digital',
    mount: 'strap',
    description:
      "Type - Man's; Movement - Quartz; Style - Sports; Dial type - Electronic; Fastening type - Strap; Glass - Mineral; Time format - 24 hours; Case shape - Round; Case material - Polycarbonate; Strap/bracelet material - Fabric; Case diameter - 46 mm;",
  },
  {
    id: 13,
    brand: 'North Edge',
    name: 'North Edge Hornet',
    price: 82,
    stock: 112,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "Type - Man's; Glass - Mineral; Dial type - Indices; Case shape - Round; Case material - Steel; Strap/bracelet material - Rubber; Characteristics of the mechanism - North Edge (Japan); Warranty - 12 months; Case color - Black;",
  },
  {
    id: 14,
    brand: 'North Edge',
    name: 'North Edge Laker Black 5BAR',
    price: 68,
    stock: 93,
    clockFace: 'digital',
    mount: 'strap',
    description:
      "Type - Man's; Movement - Quartz; Style - Sports; Dial type - Electronic; Fastening type - Strap; Glass - Mineral; Case shape - Round; Case material - Polycarbonate; The main color of the dial is Black; Water resistance - 50 m; Strap/bracelet material - Rubber; Backlight - With backlight; Case dimensions (HxW) - 43 x 12 mm; Weight - 100 g; Warranty - 12 months official warranty from the manufacturer; Case color - Black; Case diameter - 43 mm;",
  },
  {
    id: 15,
    brand: 'North Edge',
    name: 'North Edge Combo 10BAR',
    price: 87,
    stock: 89,
    clockFace: 'digital',
    mount: 'strap',
    description:
      "Type - Man's; Movement - Quartz; Style - Sports; Dial type - Electronic; Fastening type - Strap; Dial type - Arabic numerals; Case material - Plastic; The main color of the dial is Black; Strap/bracelet color - Black; Case dimensions (HxW) - 44x13 mm; Characteristics of the mechanism - Combo North Edge (Japan); Warranty - 12 months; Case diameter - 44 mm;",
  },
  {
    id: 16,
    brand: 'Seiko',
    name: 'Seiko SBDC147',
    price: 1216,
    stock: 29,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      'Movement 6R35, power reserve over 70 hours, manual and automatic winding, stop second; Case and bracelet stainless steel; Sapphire crystal with anti-reflective coating Lumibrite phosphor on hands and markers; Water resistance 200 meters; Threaded crown and back cover; Size (length x width x thickness): 46.2 x 38 x 12.9mm; Weight about 146 grams; Made in Japan;',
  },
  {
    id: 17,
    brand: 'Seiko',
    name: 'Seiko SRPH80K1',
    price: 1195,
    stock: 21,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "The model was created in collaboration with Brian May - the legendary guitarist of Queen. The inspiration was Brian's favorite Red Special guitar, which has served him for over 50 years. He made this guitar himself with his father in the 1960s. The design of the dial is reminiscent of the outlines of the same guitar. Brian May is also a big fan of Seiko watches. The movement has 24 jewels and a frequency of 21,600 vibrations per hour. Power reserve 41 hours. stop-second function. Possibility of manual winding. The bezel rotates in one direction. Transparent screw-down case back. Individual serial number. Screw-down crown with protection is at the 4 o'clock position.",
  },
  {
    id: 18,
    brand: 'Seiko',
    name: 'Seiko SPB117 Automatic Alpinist',
    price: 1190,
    stock: 22,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      'NEW movement - 6R35, 24 jewels; has a frequency of 21,600 vph and a power reserve of 70 hours; Dial - black mother-of-pearl; Glass - sapphire with cyclops lens; Screw-down crown; Compass (internal azimuth set above the dial along its circumference); Power reserve - 70 hours; Diameter - 39.5 mm; Thickness -12 mm Weight ~ 119 g; Way of display of time ― analog (pointer), a format of 12 hours; Energy source - spring mechanism; Water resistance - WR200 (20 atm); Case material ― stainless steel; Bracelet / strap material - steel; Illumination - arrows, labels;',
  },
  {
    id: 19,
    brand: 'Seiko',
    name: 'Seiko SARY183 SRPF43J1',
    price: 849,
    stock: 31,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      'Movement - 4R35, self-winding mechanics, manual winding, stop second, 23 jewels, Made in Japan; Case - stainless steel, transparent back cover; Glass ― bent domed Hardlex, crystal surpassing usual mineral glass; Functions - date; Dial - brown; Bracelet/strap - genuine leather; Clasp - folding with buttons for opening; Water resistance - 50 meters; Case diameter ― 38,5mm/41,5mm; Case thickness - 11.8mm; International guarantee - 1 year;',
  },
  {
    id: 20,
    brand: 'Seiko',
    name: 'Seiko Sportura SNDX97P1',
    price: 955,
    stock: 44,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      'Movement type: quartz; Water resistance: 100m; Time Format: 12h; Bracelet material: stainless steel, ceramic; Case material: stainless steel, ceramics; Glass: Sapphire; Housing dimensions (WxHxD): 38x38x10 mm; Luminous accumulators on arrows and marks; Functions: Date, Chronograph; Assembly factory: Japan;',
  },
  {
    id: 21,
    brand: 'TAG HEUER',
    name: 'TAG HEUER CAR5A5Y.FC6377',
    price: 19293,
    stock: 12,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "Titanium case with ceramic bezel and 18k rose gold inserts; Scratch-resistant domed sapphire crystal with anti-reflective coating on both sides; Black caseback with sapphire crystal; Fluted rose gold and rubber crown; Power reserve: 65 hours; Titanium folding clasp with black titanium carbide coating; 1-minute tourbillon with carbon and titanium cage at 6 o'clock; Applied black polished indexes with 18 carat rose gold plating and luminescent inserts; Clockwork with black skeletonized bridges; Rose gold-plated hour and minute hands with luminescent inserts; Rose gold-plated chronograph hands; Rose gold-plated central chronograph seconds hand;",
  },
  {
    id: 22,
    brand: 'TAG HEUER',
    name: 'TAG HEUER CAV5185.FT6020',
    price: 8583,
    stock: 8,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "Type - Man's; Mechanism - Mechanical; Style - Sports; Fastening type - Strap; Collection - GRAND CARRERA; Glass - Sapphire; Case shape - Round; Case material - Steel; The main color of the dial is Black; Water resistance - 100 m; Strap/bracelet material - Rubber; Assembly factory - Switzerland; Warranty - 24 months; Case color - Black; Case diameter - 43 mm;",
  },
  {
    id: 23,
    brand: 'TAG HEUER',
    name: 'TAG HEUER CBG2052.FT6143',
    price: 8022,
    stock: 9,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "Type - Man's; Mechanism - Mechanical; Style - Sports; Fastening type - Strap; Collection - Carrera; Glass - Sapphire; Case shape - Round; Case material - Steel; The main color of the dial is Black; Water resistance - 100 m; Strap/bracelet material - Rubber; Assembly factory - Switzerland; Warranty - 24 months; Case color - Multi-colored; Case diameter - 43 mm;",
  },
  {
    id: 24,
    brand: 'TAG HEUER',
    name: 'TAG HEUER WAV5152.FC6231',
    price: 4853,
    stock: 18,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "Type - Man's; Mechanism - Mechanical; Style - Sports; Fastening type - Strap; Collection - Grand Carrera GMT; Glass - Sapphire; Case shape - Round; Case material - Steel; The main color of the dial is Silver; Water resistance - 100 m; Strap/bracelet material - Leather; Assembly factory - Switzerland; Warranty - 24 months; Case color - Multi-colored; Case diameter - 42.5 mm;",
  },
  {
    id: 25,
    brand: 'TAG HEUER',
    name: 'TAG HEUER CV2A1F.BA0796',
    price: 4332,
    stock: 15,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      "Type - Man's; Mechanism - Mechanical; Style - Sports; Fastening type - Bracelet; Collection - Carrera; Functions - Date, Chronograph; Glass - Sapphire; Case shape - Round; Case material - Steel; The main color of the dial is Silver; Water resistance - 100 m; Strap/bracelet material - Steel; Assembly factory - Switzerland; Warranty - 24 months; Case color - Multi-colored; Case diameter - 43 mm;",
  },
  {
    id: 26,
    brand: 'Fossil',
    name: 'Fossil FTW4024',
    price: 445,
    stock: 21,
    clockFace: 'digital',
    mount: 'bracelet',
    description:
      "Type - Man's; Movement - Quartz; Style - Fashion; Functions - Pedometer; Glass - Mineral; Case material - Steel; Water resistance - 3 m; Strap/bracelet color - Grey; Strap/bracelet material - Steel; Strap/bracelet width - 22; Warranty - 24 months; Case color - Gray; Case diameter - 44;",
  },
  {
    id: 27,
    brand: 'Fossil',
    name: 'Fossil CH2451',
    price: 433,
    stock: 66,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      "Mineral glass is resistant to the appearance of scratches; Case and bracelet made of high quality 316L steel alloy with high anti-corrosion properties; Luminescent hands and markers; Case dimensions: diameter 42 mm; Type - Man's; Movement - Quartz; Fastening type - Bracelet; Glass - Mineral; Case material - Steel; Water resistance - 100 m; Strap/bracelet material - Steel;",
  },
  {
    id: 28,
    brand: 'Fossil',
    name: 'Fossil ME3200',
    price: 498,
    stock: 49,
    clockFace: 'pointer',
    mount: 'strap',
    description:
      "Type - Man's; Mechanism - Mechanical with automatic winding; Style - Classic; Dial type - Pointer; Glass - Mineral; Case material - Steel; The main color of the dial is Silver; Water resistance - 50 m; Strap/bracelet color - Black; Strap/bracelet material - Genuine leather; Strap/bracelet width - 22; Warranty - 24 months; Body color - Silver; Case diameter - 44;",
  },
  {
    id: 29,
    brand: 'Fossil',
    name: 'Fossil Gen 6',
    price: 531,
    stock: 61,
    clockFace: 'digital',
    mount: 'bracelet',
    description:
      "Type - Man's; Movement - Quartz; Fastening type - Bracelet; Glass - Mineral; Case shape - Round; Case material - Steel; Additional features - NFC, Alarm clock, Sleep monitoring, Stopwatch, Barometer, Heart rate monitor Altimeter, Call support, Chronograph, Second time, Backlight, Timer Compass, Day of the week indication, Month indication, Bluetooth, GPS, Pedometer, Calorie counting; The main color of the dial is Black; Water resistance - 30 m; Assembly factory - China; Warranty - 24 months; Body color - Silver; Case diameter - 44 mm;",
  },
  {
    id: 30,
    brand: 'Fossil',
    name: 'Fossil FS5707',
    price: 297,
    stock: 53,
    clockFace: 'pointer',
    mount: 'bracelet',
    description:
      "Type - Man's; Movement - Quartz; Style - Fashion; Dial type - Pointer; Fastening type - Bracelet; Glass - Mineral; Case shape - Round; Case material - Steel; The main color of the dial is Black; Water resistance - 5 m; Strap/bracelet color - Black; Strap/bracelet material - Steel; Strap/bracelet width - 22; Warranty - 24 months; Case color - Black; Case diameter - 44;",
  },
];
